from fastapi import APIRouter
from app.schemas.schemas import SymptomCheckRequest, SymptomCheckResponse

router = APIRouter(prefix="/symptoms", tags=["Symptom Checker"])

@router.post("/check", response_model=SymptomCheckResponse)
def check_symptoms(req: SymptomCheckRequest):
    symptoms_lower = [s.lower() for s in req.symptoms]
    
    # Simple risk rule engine logic
    risk_level = "Low"
    possible_conditions = []
    recommended_actions = []

    high_risk_triggers = ["chest pain", "shortness of breath", "unconsciousness", "severe bleeding", "sudden numbness"]
    moderate_risk_triggers = ["high fever", "persistent vomiting", "severe headache", "dizziness", "abdominal pain"]

    has_high_risk = any(any(hr in s for hr in high_risk_triggers) for s in symptoms_lower)
    has_mod_risk = any(any(mr in s for mr in moderate_risk_triggers) for s in symptoms_lower)

    if req.severity == "Severe" or has_high_risk:
        risk_level = "High"
        possible_conditions = ["Acute Cardiac Condition", "Severe Respiratory Distress", "Systemic Emergency"]
        recommended_actions = [
            "🚨 Seek immediate emergency medical care or call 911 / Local Emergency Line.",
            "Do not drive yourself to the hospital if experiencing severe shortness of breath or chest pain.",
            "Inform emergency personnel of all current medications."
        ]
    elif req.severity == "Moderate" or has_mod_risk or req.duration in ["1-2 weeks", "More than 2 weeks"]:
        risk_level = "Moderate"
        possible_conditions = ["Viral or Bacterial Infection", "Migraine / Tension Episode", "Inflammatory Response"]
        recommended_actions = [
            "Schedule an appointment with a primary care physician within 24-48 hours.",
            "Ensure adequate hydration and rest.",
            "Monitor body temperature and symptom progression regularly."
        ]
    else:
        risk_level = "Low"
        possible_conditions = ["Common Upper Respiratory Cold", "Mild Fatigue / Stress", "Minor Muscle Strain"]
        recommended_actions = [
            "Rest and maintain good hydration with fluids.",
            "Use over-the-counter remedies as appropriate for mild discomfort.",
            "Consult a doctor if symptoms persist past 5-7 days."
        ]

    disclaimer = "⚠️ IMPORTANT: This symptom check is generated by an automated triage algorithm for general guidance only. It is NOT a clinical diagnosis. Always consult a qualified medical professional."

    return {
        "risk_level": risk_level,
        "possible_conditions": possible_conditions,
        "recommended_actions": recommended_actions,
        "disclaimer": disclaimer
    }
